import './globals.css'
import { League_Spartan } from 'next/font/google'

const font = League_Spartan({ subsets: ['latin'], weight: ['500', '600', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
      
      
      
      {children}
      
      </body>
    </html>
  )
}
